#!/bin/bash

#PBS -N Z9
#PBS -W group_list=mse551-2017
### Set the queue for this job as windfall or standard (adjust ### and #)
#PBS -q windfall
#PBS -l jobtype=cluster_only
#PBS -l select=1:ncpus=1:mem=23GB
#PBS -l cput=1:00:00
#PBS -l walltime=1:00:00

##Change directory to where your input file is located
cd $PBS_O_WORKDIR

source /usr/share/Modules/init/tcsh
module load unsupported/krishna
module load krishna/vasp/5.3.5

time mpirun -np 1 vasp.5.3.5-intel