#!/bin/bash

#PBS -N Z9
#PBS -W group_list=krishna
### Set the queue for this job as windfall or standard (adjust ### and #)
#PBS -q standard
#PBS -l jobtype=cluster_only
#PBS -l select=4:ncpus=12:mem=23GB
#PBS -l cput=48:00:00
#PBS -l walltime=1:00:00

##Change directory to where your input file is located
cd $PBS_O_WORKDIR

source /usr/share/Modules/init/tcsh
module load unsupported/krishna
module load krishna/vasp/5.3.5

sh k_loop.sh
